const actionsTypes = {
    SEARCH_STREAM_PENDING: 'SEARCH_STREAM_PENDING',
    SEARCH_STREAM_SUCCESS: 'SEARCH_STREAM_SUCCESS',
    SEARCH_STREAM_ERROR: 'SEARCH_STREAM_ERROR'
};

export { actionsTypes };